test: &default
  client_id: <%= Rails.application.credentials.client_id %>
  client_secret: <%= Rails.application.credentials.client_secret %>
  mode: sandbox
development:
  <<: *default
  ssl_options:
    ca_file: null

production:
  <<: *default
  mode: live
